<h3><?php echo $this->__('Address Book') ?></h3>
<a href="<?php echo $this->getAddressBookUrl() ?>"><?php echo $this->__('Manage Addresses') ?></a>
<div class="row">
    <div class="large-6">
        <h4><?php echo $this->__('Default Billing Address') ?></h4>
        <address>
            <?php echo $this->getPrimaryBillingAddressHtml() ?><br />
            <a href="<?php echo $this->getPrimaryBillingAddressEditUrl() ?>"><?php echo $this->__('Edit Address') ?></a>
        </address>
    </div>
    <div class="large-6">
        <h4><?php echo $this->__('Default Shipping Address') ?></h4>
        <address>
            <?php echo $this->getPrimaryShippingAddressHtml() ?><br />
            <a href="<?php echo $this->getPrimaryShippingAddressEditUrl() ?>"><?php echo $this->__('Edit Address') ?></a>
        </address>
    </div>
</div>
