<div class="row">
    <div class="large-6">
        <h3><?php echo $this->__('Contact Information') ?></h3>
        <a href="<?php echo $this->getUrl('customer/account/edit') ?>"><?php echo $this->__('Edit') ?></a>
        <p>
            <?php echo $this->escapeHtml($this->getCustomer()->getName()) ?><br />
            <?php echo $this->escapeHtml($this->getCustomer()->getEmail()) ?><br />
            <a href="<?php echo $this->getChangePasswordUrl() ?>"><?php echo $this->__('Change Password') ?></a>
        </p>
    </div>
    <?php if( $this->isNewsletterEnabled() ): ?>
    <div class="large-6">
        <h3><?php echo $this->__('Newsletters') ?></h3>
        <a href="<?php echo $this->getUrl('newsletter/manage') ?>"><?php echo $this->__('Edit') ?></a>
        <p>
        <?php if( $this->getIsSubscribed() ): ?>
            <?php echo $this->__("You are currently subscribed to 'General Subscription'.") ?>
        <?php else: ?>
            <?php echo $this->__('You are currently not subscribed to any newsletter.') ?>
        <?php endif; ?>
        </p>
    </div>
    <?php echo $this->getChildHtml('customer.account.dashboard.info.extra')?>
    <?php endif; ?>
</div>
