<h1><?php echo $this->__('Edit Account Information') ?></h1>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<form action="<?php echo $this->getUrl('customer/account/editPost') ?>" method="post" id="form-validate" autocomplete="off">
    <?php echo $this->getBlockHtml('formkey')?>
    <h2><?php echo $this->__('Account Information') ?></h2>
    <ul class="form-list">
        <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getCustomer())->toHtml() ?>
        <li>
            <label for="email" class="required"><?php echo $this->__('Email Address') ?> <em>*</em></label>
            <input type="text" name="email" id="email" value="<?php echo $this->escapeHtml($this->getCustomer()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" class="input-text required-entry validate-email" />
        </li>
    <?php $_dob = $this->getLayout()->createBlock('customer/widget_dob') ?>
    <?php if ($_dob->isEnabled()): ?>
        <li><?php echo $_dob->setDate($this->getCustomer()->getDob())->toHtml() ?></li>
    <?php endif ?>
    <?php $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat') ?>
    <?php if ($_taxvat->isEnabled()): ?>
        <li><?php echo $_taxvat->setTaxvat($this->getCustomer()->getTaxvat())->toHtml() ?></li>
    <?php endif ?>
    <?php $_gender = $this->getLayout()->createBlock('customer/widget_gender') ?>
    <?php if ($_gender->isEnabled()): ?>
        <li><?php echo $_gender->setGender($this->getCustomer()->getGender())->toHtml() ?></li>
    <?php endif ?>
        <li class="control">
            <input type="checkbox" name="change_password" id="change_password" value="1" onclick="setPasswordForm(this.checked)" title="<?php echo $this->__('Change Password') ?>"<?php if($this->getCustomer()->getChangePassword()==1): ?> checked="checked"<?php endif; ?> class="checkbox" /><label for="change_password"><?php echo $this->__('Change Password') ?></label>
        </li>
    </ul>
    <div class="password-form" style="display:none;">
        <h2><?php echo $this->__('Change Password') ?></h2>
        <ul class="form-list">
            <li>
                <label for="current_password" class="required"><?php echo $this->__('Current Password') ?> <em>*</em></label>
                <input type="password" title="<?php echo $this->__('Current Password') ?>" class="input-text" name="current_password" id="current_password" />
            </li>
            <li>
                <label for="password" class="required"><?php echo $this->__('New Password') ?> <em>*</em></label>
                <input type="password" title="<?php echo $this->__('New Password') ?>" class="input-text validate-password" name="password" id="password" />
            </li>
            <li>
                <label for="confirmation" class="required"><?php echo $this->__('Confirm New Password') ?> <em>*</em></label>
                <input type="password" title="<?php echo $this->__('Confirm New Password') ?>" class="input-text validate-cpassword" name="confirmation" id="confirmation" />
            </li>
        </ul>
    </div>
    <p class="required"><?php echo $this->__('* Required Fields') ?></p>
    <button type="submit" title="<?php echo $this->__('Save') ?>" class="button"><?php echo $this->__('Save') ?></button>
</form>
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
    function setPasswordForm(arg){
        if(arg){
            $$('.password-form')[0].show();
            $('current_password').addClassName('required-entry');
            $('password').addClassName('required-entry');
            $('confirmation').addClassName('required-entry');

        }else{
            $$('.password-form')[0].hide();
            $('current_password').removeClassName('required-entry');
            $('password').removeClassName('required-entry');
            $('confirmation').removeClassName('required-entry');
        }
    }

    <?php if($this->getCustomer()->getChangePassword()): ?>
        setPasswordForm(true);
    <?php endif; ?>
//]]>
</script>
