<h1><?php echo $this->__('Forgot Your Password?') ?></h1>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<form action="<?php echo $this->getUrl('*/*/forgotpasswordpost') ?>" method="post" id="form-validate">
    <h2><?php echo $this->__('Retrieve your password here') ?></h2>
    <p><?php echo $this->__('Please enter your email address below. You will receive a link to reset your password.') ?></p>
    <ul class="form-list">
        <li>
            <label for="email_address" class="required"><?php echo $this->__('Email Address') ?> <em>*</em></label>
            <input type="text" name="email" alt="email" id="email_address" class="input-text required-entry validate-email" value="<?php echo $this->escapeHtml($this->getEmailValue()) ?>" />
        </li>
        <?php echo $this->getChildHtml('form.additional.info'); ?>
    </ul>
    <p class="required"><?php echo $this->__('* Required Fields') ?></p>
    <button type="submit" title="<?php echo $this->__('Submit') ?>" class="button"><?php echo $this->__('Submit') ?></button>
</form>
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
//]]>
</script>
