<h1><?php echo $this->__('My Dashboard') ?></h1>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php echo $this->getChildHtml('hello') ?>
<?php //echo $this->getChildHtml('top') ?>
<?php echo $this->getChildHtml('customer.account.dashboard.extra') ?>
<?php echo $this->getChildHtml('info') ?>
<?php echo $this->getChildHtml('address') ?>
<?php echo $this->getChildHtml('info1') ?>
<?php echo $this->getChildHtml('info2') ?>
