<div class="row table-foot">
    <div class="large-9 text-right" style="<?php echo $this->getTotal()->getStyle() ?>">
        <?php echo $this->escapeHtml($this->getTotal()->getTitle()); ?>
    </div>
    <div class="large-3 text-right" style="<?php echo $this->getTotal()->getStyle() ?>">
        <?php echo $this->helper('checkout')->formatPrice($this->getTotal()->getValue()) ?>
    </div>
</div>
