<?php echo $this->getChildHtml('items_before'); ?>
<div id="checkout-review-table-wrapper">
    <div class="row table-head">
        <div class="large-6"><?php echo $this->__('Product Name') ?></div>
        <div class="large-2"><?php echo $this->__('Price') ?></div>
        <div class="large-2"><?php echo $this->__('Qty') ?></div>
        <div class="large-2 text-right"><?php echo $this->__('Subtotal') ?></div>
    </div>
    <?php foreach($this->getItems() as $_item): ?>
        <?php echo $this->getItemHtml($_item)?>
    <?php endforeach ?>
    <div class="margin-top-large">
        <?php echo $this->getChildHtml('totals'); ?>
    </div>
</div>
<?php echo $this->getChildHtml('items_after'); ?>
<script type="text/javascript">
//<![CDATA[
    decorateTable('checkout-review-table');
    truncateOptions();
//]]>
</script>
<div id="checkout-review-submit" class="margin-top-large">
    <?php echo $this->getChildHtml('agreements') ?>
    <div class="text-right buttons-set" id="review-buttons-container">
        <p class="left inline-with-button"><?php echo $this->__('Forgot an Item?') ?> <a href="<?php echo $this->getUrl('checkout/cart') ?>"><?php echo $this->__('Edit Your Cart') ?></a></p>
        <span class="please-wait" id="review-please-wait" style="display:none;">
            <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Submitting order information...') ?>" title="<?php echo $this->__('Submitting order information...') ?>" class="v-middle" /> <?php echo $this->__('Submitting order information...') ?>
        </span>
        <?php echo $this->getChildHtml('button') ?>
    </div>
    <script type="text/javascript">
    //<![CDATA[
        review = new Review('<?php echo $this->getUrl('checkout/onepage/saveOrder', array('form_key' => Mage::getSingleton('core/session')->getFormKey())) ?>', '<?php echo $this->getUrl('checkout/onepage/success') ?>', $('checkout-agreements'));
    //]]>
    </script>
</div>
