<h1><?php echo $this->__('Address Book') ?></h1>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<div class="row addresses-primary">
    <div class="large-6">
        <h3><?php echo $this->__('Default Billing Address') ?></h3>
        <?php if($_pAddsses = Mage::getSingleton('customer/session')->getCustomer()->getDefaultBilling()): ?>
            <address>
                <?php echo $this->getAddressHtml(Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses)) ?>
            </address>
            <p><a href="<?php echo $this->getAddressEditUrl(Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses)) ?>"><?php echo $this->__('Change Billing Address') ?></a></p>
        <?php else: ?>
            <?php echo $this->__('You have no default billing address in your address book.') ?>
        <?php endif ?>
    </div>
    <div class="large-6">
        <h3><?php echo $this->__('Default Shipping Address') ?></h3>
        <?php if($_pAddsses = Mage::getSingleton('customer/session')->getCustomer()->getDefaultShipping()): ?>
            <address>
                <?php echo $this->getAddressHtml(Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses)) ?>
            </address>
            <p><a href="<?php echo $this->getAddressEditUrl(Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses)) ?>"><?php echo $this->__('Change Shipping Address') ?></a></p>
        <?php else: ?>
            <p><?php echo $this->__('You have no default shipping address in your address book.') ?></p>
        <?php endif ?>
    </div>
</div>
<div class="row">
    <h3><?php echo $this->__('Additional Address Entries') ?></h3>
    <?php if($_pAddsses = $this->getAdditionalAddresses()): ?>
        <?php foreach($_pAddsses as $_address): ?>
        <div class="large-6">
            <address>
                <?php echo $this->getAddressHtml($_address) ?>
            </address>
            <p><a href="<?php echo $this->getUrl('customer/address/edit', array('id'=>$_address->getId())) ?>"><?php echo $this->__('Edit Address') ?></a> <span class="separator">|</span> <a href="#" class="link-remove" onclick="return deleteAddress('<?php echo $_address->getId() ?>');"><?php echo $this->__('Delete Address') ?></a></p>
        </div>
        <?php endforeach; ?>
    <?php else: ?>
        <p><?php echo $this->__('You have no additional address entries in your address book.') ?></p>
    <?php endif ?>
</div>
<button type="button" title="<?php echo $this->__('Add New Address') ?>" class="button" onclick="window.location='<?php echo $this->getAddAddressUrl() ?>';"><?php echo $this->__('Add New Address') ?></button>
<script type="text/javascript">
//<![CDATA[
    function deleteAddress(addressId) {
        if(confirm('<?php echo $this->__('Are you sure you want to delete this address?') ?>')) {
            window.location='<?php echo $this->getDeleteUrl() ?>id/'+addressId;
        }
        return false;
    }
//]]>
</script>
