<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $this->getLang() ?>" lang="<?php echo $this->getLang() ?>">
<head>
<?php echo $this->getChildHtml('head') ?>
</head>
<body<?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?>>
<?php echo $this->getChildHtml('after_body_start') ?>
<?php echo $this->getChildHtml('header') ?>
<main>
    <div class="row">
        <?php echo $this->getChildHtml('global_notices') ?>
        <?php echo $this->getChildHtml('breadcrumbs') ?>
        <?php echo $this->getChildHtml('global_messages') ?>
        <div class="row">
            <div class="large-4">
                <?php echo $this->getChildHtml('left') ?>
            </div>
            <div class="large-4">
                <?php echo $this->getChildHtml('content') ?>
            </div>
            <div class="large-4">
                <?php echo $this->getChildHtml('right') ?>
            </div>
        </div>
    </div>
</main>
<?php echo $this->getChildHtml('footer') ?>
<?php echo $this->getChildHtml('global_cookie_notice') ?>
<?php echo $this->getChildHtml('before_body_end') ?>
<?php echo $this->getAbsoluteFooter() ?>
</body>
</html>
