<?php if ($this->displayBoth()):?>
<div class="row table-foot">
    <div class="large-9 text-right" style="<?php echo $this->getStyle() ?>">
        <?php echo $this->getExcludeTaxLabel() ?>
    </div>
    <div class="large-3 text-right" style="<?php echo $this->getStyle() ?>">
        <?php echo $this->helper('checkout')->formatPrice($this->getShippingExcludeTax()) ?>
    </div>
</div>
<div class="row table-foot">
    <div class="large-9 text-right" style="<?php echo $this->getStyle() ?>">
        <?php echo $this->getIncludeTaxLabel() ?>
    </div>
    <div class="large-3 text-right" style="<?php echo $this->getStyle() ?>">
        <?php echo $this->helper('checkout')->formatPrice($this->getShippingIncludeTax()) ?>
    </div>
</div>
<?php elseif($this->displayIncludeTax()) : ?>
<div class="row table-foot">
    <div class="large-9 text-right" style="<?php echo $this->getStyle() ?>">
        <?php echo $this->getTotal()->getTitle() ?>
    </div>
    <div class="large-3 text-right" style="<?php echo $this->getStyle() ?>">
        <?php echo $this->helper('checkout')->formatPrice($this->getShippingIncludeTax()) ?>
    </div>
</div>
<?php else:?>
<div class="row table-foot">
    <div class="large-9 text-right" style="<?php echo $this->getStyle() ?>">
        <?php echo $this->escapeHtml($this->getTotal()->getTitle()) ?>
    </div>
    <div class="large-3 text-right" style="<?php echo $this->getStyle() ?>">
        <?php echo $this->helper('checkout')->formatPrice($this->getShippingExcludeTax()) ?>
    </div>
</div>
<?php endif;?>
