<?php
    $_value = $this->getTotal()->getValue();
    $_style = $this->getTotal()->getStyle();
?>
<?php global $taxIter; $taxIter++; ?>
<?php if ($this->helper('tax')->displayFullSummary() && $_value!=0): ?>
<?php $isTop = 1; ?>
    <?php foreach ($this->getTotal()->getFullInfo() as $info): ?>
        <?php if (isset($info['hidden']) && $info['hidden']) continue; ?>
        <?php $percent = $info['percent']; ?>
        <?php $amount = $info['amount']; ?>
        <?php $rates = $info['rates']; ?>
        <?php $isFirst = 1; ?>

        <?php foreach ($rates as $rate): ?>
        <div class="summary-details-<?php echo $taxIter; ?> summary-details<?php if ($isTop): echo ' summary-details-first'; endif; ?>" style="display:none;">
            <div class="a-right" style="<?php echo $_style ?>" colspan="<?php echo $this->getColspan(); ?>">
                <?php echo $this->escapeHtml($rate['title']); ?>
                <?php if (!is_null($rate['percent'])): ?>
                    (<?php echo (float)$rate['percent']; ?>%)
                <?php endif; ?>
                <br />
            </div>
            <?php if ($isFirst): ?>
                <div style="<?php echo $_style ?>" class="a-right" rowspan="<?php echo count($rates); ?>">
                    <?php echo $this->helper('checkout')->formatPrice($amount); ?>
                </div>
            <?php endif; ?>
        </div>
        <?php $isFirst = 0; ?>
        <?php $isTop = 0; ?>
        <?php endforeach; ?>
    <?php endforeach; ?>
    <?php $weees = $this->getAllWeee(); ?>
    <?php foreach ($weees as $weeeTitle => $weeeAmount): ?>
    <div class="summary-details-<?php echo $taxIter; ?> summary-details<?php if ($isTop): echo ' summary-details-first'; endif; ?>" style="display:none;">
        <div class="a-right" style="<?php echo $_style ?>" colspan="<?php echo $this->getColspan(); ?>">
            <?php echo $this->escapeHtml($weeeTitle); ?>
            <br />
        </div>
        <div style="<?php echo $_style ?>" class="a-right" rowspan="1">
            <?php echo $this->helper('checkout')->formatPrice($weeeAmount); ?>
        </div>
    </div>
    <?php endforeach; ?>
<?php endif;?>
<div class="row table-foot" <?php if ($this->helper('tax')->displayFullSummary() && $_value!=0): ?> onclick="expandDetails(this, '.summary-details-<?php echo $taxIter;?>')"<?php endif; ?>>
    <div class="large-9 text-right" style="<?php echo $_style ?>">
        <?php if ($this->helper('tax')->displayFullSummary()): ?>
            <div class="summary-collapse"><?php echo $this->getTotal()->getTitle() ?></div>
        <?php else: ?>
            <?php echo $this->getTotal()->getTitle() ?>
        <?php endif;?>
    </div>
    <div class="large-3 text-right" style="<?php echo $_style ?>"><?php echo $this->helper('checkout')->formatPrice($_value) ?></div>
</div>
