<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php $_orders = $this->getOrders(); ?>
<h1><?php echo $this->__('My Orders') ?></h1>
<?php echo $this->getPagerHtml(); ?>
<?php if($_orders->getSize()): ?>
<div class="row table-head">
    <div class="large-2 medium-12"><?php echo $this->__('Order #') ?></div>
    <div class="large-2 medium-hide"><?php echo $this->__('Date') ?></div>
    <div class="large-2 medium-hide"><?php echo $this->__('Ship To') ?></div>
    <div class="large-2 medium-hide"><?php echo $this->__('Order Total') ?></div>
    <div class="large-2 medium-hide"><?php echo $this->__('Order Status') ?></div>
    <div class="large-2 medium-hide">&nbsp;</div>
</div>
<?php foreach ($_orders as $_order): ?>
<div class="row table-body">
    <div class="large-2 medium-12"><?php echo $_order->getRealOrderId() ?></div>
    <div class="large-2 medium-12"><?php echo $this->formatDate($_order->getCreatedAtStoreDate()) ?></div>
    <div class="large-2 medium-12"><?php echo $_order->getShippingAddress() ? $this->escapeHtml($_order->getShippingAddress()->getName()) : '&nbsp;' ?></div>
    <div class="large-2 medium-12"><?php echo $_order->formatPrice($_order->getGrandTotal()) ?></div>
    <div class="large-2 medium-12"><?php echo $_order->getStatusLabel() ?></div>
    <div class="large-2 medium-12">
        <a href="<?php echo $this->getViewUrl($_order) ?>"><?php echo $this->__('View Order') ?></a>
        <?php if ($this->helper('sales/reorder')->canReorder($_order)) : ?>
            <span class="separator">|</span> <a href="<?php echo $this->getReorderUrl($_order) ?>" class="link-reorder"><?php echo $this->__('Reorder') ?></a>
        <?php endif ?>
    </div>
</div>
<?php endforeach; ?>
<?php echo $this->getPagerHtml(); ?>
<?php else: ?>
    <p><?php echo $this->__('You have placed no orders.'); ?></p>
<?php endif ?>
