<?php  $_order = $this->getOrder() ?>
<div class="row table-head">
    <div class="large-3"><?php echo $this->__('Product Name') ?></div>
    <div class="large-3"><?php echo $this->__('SKU') ?></div>
    <div class="large-2"><?php echo $this->__('Price') ?></div>
    <div class="large-2"><?php echo $this->__('Qty') ?></div>
    <div class="large-2 text-right"><?php echo $this->__('Subtotal') ?></div>
</div>
<?php $_items = $_order->getItemsCollection(); ?>
<?php $_index = 0; ?>
    <?php $_count = $_items->count(); ?>
<?php foreach ($_items as $_item): ?>
<?php if ($_item->getParentItem()) continue; ?>
    <?php echo $this->getItemHtml($_item) ?>
    <?php if($this->helper('giftmessage/message')->getIsMessagesAvailable('order_item', $_item) && $_item->getGiftMessageId()): ?>
    <div class="row" id="order-item-gift-message-<?php echo $_item->getId() ?>" style="display:none;">
        <?php $_giftMessage=$this->helper('giftmessage/message')->getGiftMessageForEntity($_item); ?>
        <a href="#" title="<?php echo $this->__('Close') ?>" onclick="return giftMessageToogle('<?php echo $_item->getId() ?>');" class="btn-close"><?php echo $this->__('Close') ?></a>
        <dl class="gift-message">
            <dt><strong><?php echo $this->__('From:') ?></strong> <?php echo $this->escapeHtml($_giftMessage->getRecipient()) ?></dt>
            <dt><strong><?php echo $this->__('To:') ?></strong> <?php echo $this->escapeHtml($_giftMessage->getSender()) ?></dt>
            <dd><?php echo $this->helper('giftmessage/message')->getEscapedGiftMessage($_item) ?></dd>
        </dl>
    </div>
    <?php endif ?>
<?php endforeach; ?>
<?php echo $this->getChildHtml('order_totals') ?>
